'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Area
    Public Property id_area As Integer
    Public Property nombre As String
    Public Property lider As Nullable(Of Integer)
    Public Property auxiliar As Nullable(Of Integer)
    Public Property cede_id As Nullable(Of Integer)
    Public Property estado As Nullable(Of Integer)
    Public Property descripcion As String

    Public Overridable Property AuxiliarArea As Persona
    Public Overridable Property Cede As Cede
    Public Overridable Property LiderArea As Persona

End Class
