'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bautizados
    Public Property id_bautizado As Integer
    Public Property estado As String
    Public Property iglesia As String
    Public Property lugar As String
    Public Property año As Nullable(Of Integer)

    Public Overridable Property Persona As ICollection(Of Persona) = New HashSet(Of Persona)

End Class
