'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cede
    Public Property id_cede As Integer
    Public Property descripcion As String
    Public Property lider As Nullable(Of Integer)
    Public Property auxiliar As Nullable(Of Integer)
    Public Property mesInicio As String
    Public Property añoInicio As Nullable(Of Integer)
    Public Property estado As Nullable(Of Integer)

    Public Overridable Property CededeCelula As ICollection(Of Celula) = New HashSet(Of Celula)
    Public Overridable Property AuxiliarCede As Persona
    Public Overridable Property LiderCede As Persona
    Public Overridable Property CedeDePersona As ICollection(Of Persona) = New HashSet(Of Persona)
    Public Overridable Property Area As ICollection(Of Area) = New HashSet(Of Area)

End Class
