'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Celula
    Public Property id_celula As Integer
    Public Property nombre As String
    Public Property lider As Nullable(Of Integer)
    Public Property auxiliar As Nullable(Of Integer)
    Public Property direccion As String
    Public Property horario As String
    Public Property dirigido As String
    Public Property mesInicio As String
    Public Property añoInicio As Nullable(Of Integer)
    Public Property estado As Nullable(Of Integer)
    Public Property cede_id As Nullable(Of Integer)
    Public Property sexo As String
    Public Property red_id As Nullable(Of Integer)

    Public Overridable Property CededeCelula As Cede
    Public Overridable Property Red As Red
    Public Overridable Property Reporte As ICollection(Of Reporte) = New HashSet(Of Reporte)
    Public Overridable Property LiderCelula As Persona
    Public Overridable Property AuxiliarCelula As Persona
    Public Overridable Property CelulaDePersona As ICollection(Of Persona) = New HashSet(Of Persona)

End Class
