'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EscuelaDeVida
    Public Property id_escuela As Integer
    Public Property descripcion As String

    Public Overridable Property Persona As ICollection(Of Persona) = New HashSet(Of Persona)

End Class
