'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Lideres
    Public Property id_lider As Integer
    Public Property persona_id As Nullable(Of Integer)
    Public Property estado As Nullable(Of Integer)
    Public Property nombre As String
    Public Property celulalider As String

    Public Overridable Property LiderDePersona As ICollection(Of Persona) = New HashSet(Of Persona)
    Public Overridable Property PersonaQueEsLider As Persona

End Class
