'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Red
    Public Property id_red As Integer
    Public Property nombre As String
    Public Property estado As Nullable(Of Integer)

    Public Overridable Property Celula As ICollection(Of Celula) = New HashSet(Of Celula)
    Public Overridable Property Reporte As ICollection(Of Reporte) = New HashSet(Of Reporte)

End Class
