'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Reporte
    Public Property id_reporte As Integer
    Public Property red_id As Nullable(Of Integer)
    Public Property celula_id As Nullable(Of Integer)
    Public Property lider As String
    Public Property aux As String
    Public Property domicilio As String
    Public Property fecha As Nullable(Of Date)
    Public Property dia As String
    Public Property hora As String
    Public Property leccion As String
    Public Property miembros_pres As String
    Public Property visitantes As String
    Public Property total_pres As String
    Public Property discipulados As String
    Public Property bautizados As String
    Public Property almasganadas As String
    Public Property miembros_ausent As String
    Public Property observacion As String

    Public Overridable Property Celula As Celula
    Public Overridable Property Red As Red

End Class
